move_group_namespace: ""
move_group: move_group
eye_on_base: true
tracking_marker_name: ar_marker_id
robot_base_frame: robot_base_link
robot_effector_frame: robot_tool_link
eye_on_hand: false
camera_matrix: [Fx, 0, Cx, 0, Fy, Cy, 0, 0, 1]
camera_distortion: [k1, k2, p1, p2, k3]
tracking_base_frame: camera_link
tracking_marker_frame: ar_marker_frame
freehand_robot_movement: false